### ISSUE TITLE
Facebook cache clearing

### ISSUE THREAD

**Issue by amyhughes** [guardian/social-cache-clearing#1]
I _think_ this is working for Facebook, at least as far as article titles are concerned.

A request was made at 14:25 to Facebook Graph API for this URL:

> "url": "http://www.theguardian.com/uk-news/2019/mar/07/mod-challenged-over-ludicrous-claim-of-one-civilian-death-in-isis-raids"

Returning metadata for the title of:

> "title": "MoD claim of one civilian death in Isis raids called ludicrous"

At 14:28 another request was made for the same URL, this time returning different title metadata:

> "title": "MoD claim of one civilian death in Isis raids ridiculed"

(See Cloudwatch logs [here](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logEventViewer:group=/aws/lambda/socialCacheClearing-PROD;filter=%22Isis%22;start=2019-03-07T14:24:00Z;end=2019-03-07T14:30:00Z))

This updated title is the title displayed in the Facebook post:

![image](https://user-images.githubusercontent.com/9820960/53965755-af0e0500-40e9-11e9-871a-46e6c14b7b7a.png)

It's possible that the process of posting prompts a refresh of the cache, so this is not a strict test.

cc @LATaylor-guardian

**Comment by amyhughes** [comment]
I've just tried a new test on an article @rtyley and I published on Friday. Roberto has kindly [shared it on Facebook](https://www.facebook.com/roberto.tyley/posts/10155995722221881) so I can test to see if changes made to the article are reflected on the post.

At 14:35 I changed the article title through Composer
at 14:35:21 we see the Lambda being triggered, although the response has the old title:
```
sending Facebook decache request for http://www.theguardian.com/info/2019/mar/08/has-mary-wollstonecrafts-cpu-spiked
response code: 200, response: HttpResponse(
{
    "url": "http://www.theguardian.com/info/2019/mar/08/has-mary-wollstonecrafts-cpu-spiked",
    "type": "article",
    "title": "Has Mary Wollstonecraft's CPU spiked?",
  ...
}
```

A few minutes later I try running the Lambda locally, and send an id with the campaign code attached:
```
Running socialCacheClearing.Main info/2019/mar/08/has-mary-wollstonecrafts-cpu-spiked?CMP=roberto_test_gu
sending Facebook decache request for http://www.theguardian.com/info/2019/mar/08/has-mary-wollstonecrafts-cpu-spiked?CMP=roberto_test_gu
```
This time we do see the updated title attribute in the response, suggesting that Facebook has retrieved the correct title metadata, but the post still shows the old title:
```
response code: 200, response: HttpResponse(
{
"url":"http:\/\/www.theguardian.com\/info\/2019\/mar\/08\/has-mary-wollstonecrafts-cpu-spiked",
"type":"article",
"title":"Has Margaret Atwood's CPU spiked?",...
}
)
```
![image](https://user-images.githubusercontent.com/9820960/54134587-273d3900-4410-11e9-8138-b3d27a6183a1.png)

I then try sending the POST request via a curl expression
curl -X POST \
>      -F "id=http://www.theguardian.com/info/2019/mar/08/has-mary-wollstonecrafts-cpu-spiked" \
>      -F "scrape=true" \
>      -F "access_token=(access_token)" \
>      "https://graph.facebook.com"
Which again gives the updated title in the response, but the change isn't reflected on the post
```
{
"url":"http:\/\/www.theguardian.com\/info\/2019\/mar\/08\/has-mary-wollstonecrafts-cpu-spiked",
"type":"article",
"title":"Has Margaret Atwood's CPU spiked?"
,...
}
```
Next I tried the curl POST request with the query string, still no luck.

I'm beginning to question whether this request is a legitimate method for updating what is displayed on posts. It has been suggested here:

[https://developers.facebook.com/docs/sharing/opengraph/using-objects#update](https://developers.facebook.com/docs/sharing/opengraph/using-objects#update)

**Comment by LATaylor-guardian** [comment]
@amyhughes does the post at the time of making the request violate any of these constraints:

```
You can always edit an object's properties, with two exceptions:

Title: Once 50 actions (likes, shares and comments) have been associated with an object, you won't be able to update its title
Type: An object's type can't be changed once it's been used in a story. See Open Graph Types for more information.
If you want to update an image for an object, we strongly suggest that the URL to the image be different than the original image URL. Caching may prevent the image from being updated.
```

**Comment by rtyley** [comment]
It might be interesting to know if performing a decache using the [Facebook debugger tool](https://developers.facebook.com/tools/debug/) is effective where the API isn't...

**Comment by mchv** [comment]
@amyhughes @rtyley After discussing with Facebook on the phone, they have clarified that the method we use to clear the cache is correct and similar to the one used by [Facebook debugger tool](https://developers.facebook.com/tools/debug/).  They have as well explained that existing "share" can not be updated, only new "share" will use updated metadata from the Graph

**Comment by amyhughes** [comment]
Chris Moran has reached out to Twitter re decaching, requested comment on below:

> From: Chris Moran <chris.moran@theguardian.com>
> Date: Fri, 5 Apr 2019 at 11:34
> Subject: Twitter card validator api
> 
> Hi there. In working on our timestamps on social cards we've been looking again at other problems relating to the decaching of articles on Twitter.
> 
> One particular problem we have that we'd really like your help with relates to the very common issue of updating headlines on stories and particularly live blogs as events develop.
> 
> Currently we have to manually decache each article as it changes. This is really cumbersome and difficult but also really essential to make sure that, particularly on a platform as up-to-the-second as Twitter, our editorial decisions are clearly communicated to the user.
> 
> The other issue of some gravity here is that we often change headlines for sensitivity or legal reasons or to reduce legal risk post publication.
> 
> Our question is whether Twitter would consider providing an api for the card validator that would allow us to automate this system by spotting changes on urls at our end and automatically submitting them for decaching. This would also help us when we spot spikes to older content being shared erroneously where we want the timestamp to appear as quickly as possible.
> 
> Thanks for reading and do please let us know if we could start a conversation on this.

We suggested:
> From: Roberto Tyley
> Date: Fri, 5 Apr 2019 at 12:11
> Subject: Re: Twitter card validator api
> 
> Yep, looks email good to us. Specifically, we want to ask for a Twitter API that will let us perform the decache that occurs when we hit 'Preview Card' on the 'Card Validator' at [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)
> 
> image.png
> 
> Amy & I have been looking at various techniques of decaching twitter cards, and driving https://cards-dev.twitter.com/validator is the only one that's effective. Twitter appears to use the full article url (including query parameters) as the cache key, meaning that the bit.ly-based techniques for busting-cache in [Twitter's card-troubleshooting guide](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/troubleshooting-cards.html#refreshing) aren't useful for decaching existing (eg canonical) shared urls - only changing the url of the Guardian article would save you and trigger a re-fetch.

Alex Ware suggested:

> From: Alex Ware <alex.ware@theguardian.com>
> Date: Fri, 5 Apr 2019 at 12:17
> Subject: Re: Twitter card validator api
> 
> This looks good to me, I'd also ask for a way to get (or decache) all shared urls for a canonical url. 

Twitter have responded with:

> On Tue, 4 Jun 2019, 06:55 Heather Bowen, <hbowen@twitter.com> wrote:
> Hi Matt,
> 
> Nick Pickles and I have been talking about the brilliant timestamp feature The Guardian are working on for their social channels.
> 
> We'd love to support you in this further and, as such, would like to whitelist 
> The Guardian for access to the API.
> 
> If you're interested in this, we'll need the following details to move forward. 
> The app ID for the app you will use for doing development and in production.
> 
> A few lines about what the app will be used for, for context, which includes details such as the estimated volume of pings.
> >>>>>>>>>>>>>
> 
> For background:
> 
> The URLs refresh endpoint requires whitelisted access, and is authenticated using 3-legged OAuth (user authentication). 
> 
> Unless you have an existing Twitter App (registered via apps.twitter.com) for integrating with your CMS, we recommend that you create a new one for this purpose.
> 
> For access, you will need to send your application ID to your Twitter Account representative (who is me, as I'm the partner manager who specifically looks after The Guardian) who can help to arrange this for you. 
> 
> The application ID is the number that is part of the URL when you view your app at apps.twitter.com.
> 
> You should ensure that your app has read and write access to the Twitter API since this API endpoint uses POST operations.
> 
> You can generate both Consumer Key and Secret, and an Account Token and Secret (for your logged-in account) via apps.twitter.com. These four values are required as part of the OAuth process for this endpoint.
> 
> 
> See the image below for an overview of where to find these settings and values.
> 
> 
![image](https://user-images.githubusercontent.com/9820960/59262559-58a7e980-8c37-11e9-8048-80c539b62ec1.png)
> 
> Thanks Matt,
> 
> Heather
